<?php
/**
 * @category  Trustedshops
 * @package   Trustedshops_Trustedshops
 * @author    Trusted Shops GmbH
 * @copyright 2016 Trusted Shops GmbH
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.trustedshops.de/
 */
?>
<?php /** @var Trustedshops_Trustedshops_Block_Review_Tab $this */ ?>
<?php
/**
 * content element for trustedshops review
 * will be added as additional block to product tabs
 */
?>
<div id="ts_product_sticker"></div>