<?php
/**
 * @category  Trustedshops
 * @package   Trustedshops_Trustedshops
 * @author    Trusted Shops GmbH
 * @copyright 2016 Trusted Shops GmbH
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.trustedshops.de/
 */
?>
<?php /** @var Trustedshops_Trustedshops_Block_Product_Review $this */ ?>
<?php if ($this->isActive()) : ?>
    <?php if ($this->isExpert()) : ?>
        <?php echo $this->getCode() ?>
    <?php else : ?>
        <script type="text/javascript">
            _tsProductReviewsConfig = {
                tsid: '<?php echo $this->getTsId() ?>',
                sku: ['<?php echo $this->getProductSku() ?>'],
                variant: 'productreviews',
                borderColor: '<?php echo $this->getBorderColor() ?>',
                locale: '<?php echo $this->getLocale() ?>',
                backgroundColor: ' #ffffff',
                starColor: '<?php echo $this->getStarColor() ?>',
                starSize: '15px',
                ratingSummary: 'false',
                maxHeight: '1200px',
                'element': '#ts_product_sticker',
                hideEmptySticker: 'false',
                introtext: '' /* optional */
            };
            var scripts = document.getElementsByTagName('SCRIPT'),
                me = scripts[scripts.length - 1];
            var _ts = document.createElement('SCRIPT');
            _ts.type = 'text/javascript';
            _ts.async = true;
            _ts.charset = 'utf-8';
            _ts.src
                = '//widgets.trustedshops.com/reviews/tsSticker/tsProductSticker.js';
            me.parentNode.insertBefore(_ts, me);
            _tsProductReviewsConfig.script = _ts;
        </script>
    <?php endif; ?>
<?php endif; ?>

